### ISSUE TITLE
yarn add aws-amplify error

### ISSUE THREAD

**Issue by jamesvsshark** [aws/aws-amplify#1048]
Hi all,

Great library, attempting to make the move from react-cognito to AWS amplify. We use Yarn for our package manager and seeing the below error during install:

`Couldn't find package "@types/paho-mqtt@^1.0.3" required by "aws-amplify@^0.4.4" on the "npm" registry.`

Yarn -v 1.7.0

Tried clearing node_modules directory and removed yarn lock file but continue to get the above error.

Thank you!

**Comment by haverchuck** [comment]
Hi @jamesvsshark ,

Thanks for reaching out.  I'm currently unable to reproduce your issue using a simple create-react-app setup.   Will you please clarify a couple of things?

1.  Please confirm that you are using a React applicaiton (I'm assuming the answer is yes since you were migrating from react-cognito).
2.  You are seeing this error after executing the `yarn add aws-amplify` command?

**Comment by jamesvsshark** [comment]
Hey sorry I missed the notification of your comment. My app is a react app but it was not created with CRA but I was able to resolve the issue by adding this line into my .yarnrc file

`registry "https://registry.npmjs.org"`

Thanks for your help and your attention!
