### ISSUE TITLE
Non-*amazon.com Domains Don't Work

### ISSUE THREAD

**Issue by jpeters71** [aws/aws-amplify#106]
We're using the AWS API gateway but with a custom domain (using CloudFront) in front of it. For example, using say my.api.com which maps to our AWS API gateway. When we do, we're seeing the exception below:

index.js:311 Uncaught (in promise) TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (index.js:311)
    at from (index.js:137)
    at new Buffer (index.js:113)
    at Object.update (index.js:43)
    at encrypt (Signer.js:18)
    at get_signing_key (Signer.js:149)
    at Function.sign (Signer.js:221)
    at RestClient../node_modules/aws-amplify/lib/API/RestClient.js.RestClient._signed (RestClient.js:194)
    at RestClient.js:128
    at < anonymous >

If we use the "raw" URL for the API gateway (i.e. https://<api id>.execute-api.<region>.amazonaws.com), everything works just fine.

It _looks_ like the parse_service_info inside Signer.ts is trying to parse out the service information from the host name.  I'm not seeing anyway to pass this through the api module.

An easy fix for this might be to allow clients to pass in the service information in the API.endpoints configuration.  If it's passed in, then use it.  If not, try to parse the host like it does now...just a thought.

**Comment by mlabieniec** [comment]
this is related to #71 which is in our backlog

**Comment by jpeters71** [comment]
I don't see how #71 fixes this issue...maybe I'm missing something.  This is not a case of federated logins; the login is directly against cognito the catch is that instead of hitting the raw API gateway URL, we're going through a custom domain in CloudFront that proxies the request to the API gateway. The signer is assuming the path for the service is in the amazonaws.com domain:
 
```
var parse_service_info = function (request) {
    var url_info = url.parse(request.url), host = url_info.host;
    var matched = host.match(/([^\.]+)\.(?:([^\.]*)\.)?amazonaws\.com$/);
    var parsed = (matched || []).slice(1, 3);
    if (parsed[1] === 'es') {
        parsed = parsed.reverse();
    }
    return {
        service: request.service || parsed[0],
        region: request.region || parsed[1]
    };
};
```

It seems to me that if the domain is not in *amazonaws.com, this fails.

Am I missing something?

**Comment by chapeljuice** [comment]
Agreed. Can we re-open this?

**Comment by jonsmirl** [comment]
I just hit this and for the same reason as the initial bug, I put Cloudfront in front of my APIGateway domain. Why did I do that? So that everything is on the same domain to get rid of CORS.

This is nothing to do with persistent logins. There is code in parse_service_info that forces the domain name to end in amazonaws.com. And that is not a valid assumption when either 1) you are using custom domains with APIGW, or 2) you put Cloudfront in front of APIGW. In both cases the domain will not end in amazonaws.com

At a more general level what is broken is the S3 proxy function in APIGW. If I add an S3 proxy to APIGW I incur an APIGW charge for every S3  access even though APIGW is doing nothing to the request except passing it back to S3 via the internal Cloudfront distribution it made.

So to work around this pointless charge, people make another Cloudfront distribution and have it directly proxy S3. Then add an origin to this distribution which simply points to the internal APIGW cloudfront distribution.

The need for this second Cloudfront layer could be removed if the S3 proxy inside APIGW did not incur additional APIGW charges.

**Comment by BerndWessels** [comment]
+1 I also have my APIGateway endpoint behind my custom domain with CloudFront. My site is on `platform.com` while my API is on `api.platform.com`.

So it seems we need an urgent fix for this, since it is not only a legitimate but most likely the most common case for amplify users.

@jonsmirl Do you have a temporary workaround/fix I could use?

**Comment by jonsmirl** [comment]
I hacked into the amplify source down in RestClient and hardcoded in a service_info structure.  Once I got past that I hit all of the normal CORS problems.   While working on those I concluded that the URL doesn't really matter, I removed my hacks and started using the cloudfront URL for the API.

The more interesting bit I have discovered is that you can set 'maxAge' on CORS in ApiGateway. That tells the browser to cache the CORS authorization.  So set the CORS origin to your react app (not *) and then turn on maxAge for 5-10 minutes.  Now you will only get a pre-flight once every 10 minutes instead of every call.  

My main problem was with the preflights making everything slower.  Once I figured out how to cache them the need for using a different URL went away.  

BTW - even if your api is on api.platform.com, the direct cloudfront URL also works at the same time.

**Comment by BerndWessels** [comment]
@jonsmirl Thanks for discovering all this.

I am not having my API behind a custom domain because of CORS issues but rather because I must expose a proper domain name endpoint for the API reflecting the company it represents.

The problem for me remains that `aws-amplify` does not work with custom domains for API calls.

So I will fork and use the hack you described for now, but really hope this gets fixed soon.

**Comment by jonsmirl** [comment]
@BerndWessels   you can use both domain names simultaneously -- code your amplify app to use the invoke url and give the customers the custom URL.

**Comment by BerndWessels** [comment]
That doesn't solve the fact that amplify can't call APIs behind a custom domain cloudfront distribution.

**Comment by mlabieniec** [comment]
@BerndWessels @jonsmirl Just a quick update we have a fix for this with updates to the signer, I'll try to get them in the next release.
