### ISSUE TITLE
Annoying pinpoint project analytics requests (even if the feature is disabled in the Mobile Hub Service)

### ISSUE THREAD

**Issue by josoroma** [aws/aws-amplify#1072]
Just after a user logs into the system, a set of 400 bad request responses are back from the following endpoint: `https://pinpoint.us-east-1.amazonaws.com`, with a request payload that sends  Demographic and User information.

I already disabled the Messaging and Analytics backend feature in the Mobile Hub, then I ran `awsmobile pull`, buuut messages continue to be shown on the console.

![image](https://user-images.githubusercontent.com/69951/41691829-0a206a48-74ba-11e8-8c88-b1d2338d7cc3.png)

```
    "aws-amplify": "^0.4.5",
    "aws-amplify-react": "^0.1.51",
```

I am probably missing something.

Thanks

**Comment by haverchuck** [comment]
Hi @josoroma 

Thanks for reaching out.  

I understand you attempted to disable this in mobile hub and then pulled down into your project, but what happens If you  execute:

`awsmobile analytics disable`
`awsmobile push`

This should prevent the requests from firing at all.

If it does not, check you aws-exports file.  Is there anything about analytics in there?

**Comment by josoroma** [comment]
@haverchuck it works, thanks!!!
