### ISSUE TITLE
aws-amplify-angular is only support angular5 now. will that package update soon?

### ISSUE THREAD

**Issue by caojianfei** [aws/aws-amplify#1107]
In angular 6.x , aws-amplify-angular is no longer supported

**Comment by haverchuck** [comment]
Hi @caojianfei ,

Thanks for reaching out.  Angular 6 should be supported.  Due to the elimination of the 'global' object in Angular 6 (which some of our dependencies rely on) you'll need to add a shin to your application as described [here](https://aws.github.io/aws-amplify/media/angular_guide#angular-6-support).

Please let us know if this doesn't help.
