### ISSUE TITLE
Built-in cognito page does not return the refresh_token

### ISSUE THREAD

**Issue by koorukuroo** [aws/aws-amplify#1231]
I love the cognito built-in login page, but it does not return the refresh_token
Of course, the option is that "response_type=token"

I can only have the following information using built-in page
- access_token
- id_token
- token_type
- expires_in

Why do not return the refresh_token?

**Comment by izzy26** [comment]
That's because you're using the Implicit grant. In order to get the refresh token, you would have to use the Authorization code grant (`response_type=code`).
Which one you choose depends on what kind of app are you building. You can read more on that on the [auth0 docs page](https://auth0.com/docs/api-auth/which-oauth-flow-to-use#is-the-application-a-native-app-or-a-spa-).

**Comment by koorukuroo** [comment]
Thank you so much @izzy26 ! 👍 
You solved all my problem.

I didn't know the role of 'code' value.

I refer this page https://docs.aws.amazon.com/cognito/latest/developerguide/token-endpoint.html
and this issue https://github.com/aws/amazon-cognito-auth-js/issues/52

**Comment by izzy26** [comment]
Glad to help :) Be careful though: if you are developing a javascript web app (SPA) that runs in the user's browser, using the Authorization code grant is not safe (as explained in the linked article in my previous post).

**Comment by jordanranz** [comment]
Thanks @izzy26 for your help. I am going to go ahead and close this issue. Feel free to reopen if you have any related questions or concerns.
