### ISSUE TITLE
How to get the full type definitions in typescript?

### ISSUE THREAD

**Issue by olivoil** [aws/aws-amplify#138]
Looks like types are not fully exported. `lib/Auth/index.d.ts` for instance only contains:

```typescript
declare const Auth: any;
export default Auth;
```

Is there a way to install this library from yarn/npm, use it from typescript and get the full type definitions? If not, it would be useful to flesh out the `index.d.ts` files throughout.

**Comment by buggy** [comment]
I noticed that aws-amplify is written in TypeScript but aws-amplify-react uses JavaScript. I'm willing to put the effort in to convert it from JavaScript to TypeScript if you would accept a PR. This would make generating the types trivial :)

**Comment by jonburs** [comment]
The problem here is a combination of "noImplicitAny" being set to false in tsconfig.json, and the lack of type details in Auth/index.ts:

```javascript
let _instance = null;

if (!_instance) {
    logger.debug('Create Auth Instance');
    _instance = new AuthClass(null);
}

const Auth = _instance;
export default Auth;
```

Changing the second-to-last line to

```javascript
const Auth: AuthClass = _instance;
```

results in lib/Auth/index.d.ts having the correct type definitions for Auth (which then leads to improvements in the outputted definitions for a number of other modules)

In part the typescript compiler is letting these partial definitions escape due to setting "noImplicitAny" to false in tsconfig.json...
