### ISSUE TITLE
Remove AuthPiece component in react package due to inheritance

### ISSUE THREAD

**Issue by jkettmann** [aws/aws-amplify#157]
Auth components like `ConfirmSignIn` extend `AuthPiece` which extends `React.Component`. This is not good practice (compare [facebook docs](https://reactjs.org/docs/composition-vs-inheritance.html#so-what-about-inheritance)). Use a higher order component to abstract away common behaviour.

**Comment by mlabieniec** [comment]
@jkettmann thanks for the feedback! We review this in our next sprint.

**Comment by richardzcode** [comment]
The original specific reason we introduce inheritance via AuthPiece is for handleInputChange. Because React doesn't have two way binding like VueJs. Inheritance here abstract out the boilerplate code and is clear.

React is still Javascript. While we respect folks at Facebook very much they only represent a small piece of JS community. Other voice should be allowed. The focus is does the code provide more value than tradeoff. In my opinion as of now AuthPiece provides more value.
