### ISSUE TITLE
Would like to better understand the benefits of using AWS Amplify Authentication.

### ISSUE THREAD

**Issue by palafranchise** [aws/aws-amplify#19]
This looks like an awesome new tool. Can you help me answer the following question?

When not using aws-amplify-react or aws-amplify-react-native what is the main benefit of using the AWS Amplify Auth module over using Cognito directly?

**Comment by richardzcode** [comment]
Goal of AWS Amplify Auth is to make common tasks easy, let developer focus on their business differentiators.

Amazon Cognito signUp:
```
var poolData = {
        UserPoolId : '...', // Your user pool id here
        ClientId : '...' // Your client id here
    };
    var userPool = new AWSCognito.CognitoIdentityServiceProvider.CognitoUserPool(poolData);

    var attributeList = [];

    var dataEmail = {
        Name : 'email',
        Value : 'email@mydomain.com'
    };

    var dataPhoneNumber = {
        Name : 'phone_number',
        Value : '+15555555555'
    };
    var attributeEmail = new AWSCognito.CognitoIdentityServiceProvider.CognitoUserAttribute(dataEmail);
    var attributePhoneNumber = new AWSCognito.CognitoIdentityServiceProvider.CognitoUserAttribute(dataPhoneNumber);

    attributeList.push(attributeEmail);
    attributeList.push(attributePhoneNumber);

    userPool.signUp('username', 'password', attributeList, null, function(err, result){
        if (err) {
            alert(err);
            return;
        }
        cognitoUser = result.user;
        console.log('user name is ' + cognitoUser.getUsername());
    });
```

AWS Amplify signUp:
```
Amplify.configure(aws_exports);

Auth.signUp('username', 'password', 'email@mydomain.com', '+15555555555')
    .then(user => console.log(user))
    .catch(err => console.log(err));
```

**Comment by undefobj** [comment]
Amplify also manages **AWS Credentials** gathered from Amazon Cognito Federated Identities (the above example is for Amazon Cognito User Pools). For example Instead of following [this process](http://docs.aws.amazon.com/cognito/latest/developerguide/getting-credentials.html#getting-credentials-1.javascript) and then [signing](http://docs.aws.amazon.com/general/latest/gr/signature-version-4.html), such as sending requests to Amazon API Gateway, Amplify does this all under the covers for you.
