### ISSUE TITLE
XHR Fails Loading OPTIONS

### ISSUE THREAD

**Issue by smp** [aws/aws-amplify#20]
After running through the developer guide for both react web/native, I do not see the 'up-tick in graphs' mentioned [here](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/react-native-add-analytics.html) and instead receive the following network errors in Chrome:

_XHR failed to load: OPTIONS "https://mobileanalytics.us-west-2.amazonaws.com/2014-06-05/events"_ 

_OPTIONS https://mobileanalytics.us-west-2.amazonaws.com/2014-06-05/events net::ERR_NAME_NOT_RESOLVED_

Presumably, there is something hindering the Amazon Mobile Analytics SDK from successfully calling the service, but I'm stuck attempting to troubleshoot. This issue occurs in both Chrome and Safari. Any advice or suggestions?

**Comment by richardzcode** [comment]
Hey Shawn could you get the latest aws-amplify and have a try? The issue was that endpoint not reachable.

You may add this line to your code to see more logs to be sure: Amplify.Logger.LOG_LEVEL = 'DEBUG';

**Comment by smp** [comment]
Success!!

**Comment by gitsome** [comment]
For others... we were using Firehouse instead of Amplify Analytics. By default it seems Amplify Analytics tries to record events even if you don't have things configured. We disabled it and then it doesn't send out requests and avoids this error. See this documentation for setting the disabled flag to true and autoSessionRecord to false:

https://aws.github.io/aws-amplify/media/analytics_guide
