### ISSUE TITLE
Signin form doesn't show when I do hideDefault={true}

### ISSUE THREAD

**Issue by lolcoolkat** [aws/aws-amplify#231]
I'm trying to only get the signin form to show up on this page... and when I put the hideDefault={true} nothing is displayed on the screen (if I remove it 2 signin boxes show up).

Btw my import is `import { Authenticator, SignIn as Signin } from "aws-amplify-react";` so don't worry about it being called Signin :)

I've tried all the other forms aswell, SignUp, etc and they won't show up either?

![issue](https://image.prntscr.com/image/x7YZuq_9TDOBIAYrSddDXg.png)

Any ideas? Thanks!

**Comment by yuyokk** [comment]
@lolcoolkat looking at [the source code](https://github.com/aws/aws-amplify/blob/58acf0059d3b5411506b57a467ca0cc5bc4aac2a/packages/aws-amplify-react/src/Auth/Authenticator.jsx#L106-L117) I can see that setting `hideDefault` will hide *all the default forms* so you can create custom forms.

In case you want to hide some of the default forms, you can explicitly pass what forms you want to hide via a `hide` prop instead of `hideDefault`

e.g.
```
import { Authenticator, SignUp, ConfirmSignUp } from 'aws-amplify-react';

export default class App extends Component {
  render() {
    return <Authenticator hide={[SignUp, ConfirmSignUp]} />;
  }
}
```

Hope this helps.

**Comment by lolcoolkat** [comment]
Thank you @yuyokk :)
