### ISSUE TITLE
Warnings in console with adding custom UI to Authenticator

### ISSUE THREAD

**Issue by lolcoolkat** [aws/aws-amplify#234]
Here is a little snippet of what my render function looks like.. basically I want to render my own login form but still use the Authenticator with amplify.

![Render](https://image.prntscr.com/image/CrmVm1XSQeis-FxndAxJ7Q.png)

However in my console when I run the program.. I get a ton of errors in the console like so...

![Errors](https://image.prntscr.com/image/GGxYMV3bR0m-yvxbPIj_9w.png)

Anyone have any ideas what im doing wrong? :)

**Comment by yuyokk** [comment]
This issue is described on the official docs https://reactjs.org/warnings/unknown-prop.html

I'm not sure what `grid` library is used in your case but it seems that `<Grid>` component is trying to pass down all of the props that are set from here https://github.com/aws/aws-amplify/blob/4cc30296d3af3180c1f3d2d426e03e9551c91afa/packages/aws-amplify-react/src/Auth/Authenticator.jsx#L108-L118

What I mean `Authenticator` is passing down e.g. `messageMap` to `Grid` and grid returns something like this `<div {...this.props}>{this.props.children}</div>` what results into the warning `React does not recognize the messageMap prop on a DOM element`

@lolcoolkat as a solution you can write your own Form component that will render the Grid so this way all these props will be attached to a Component instead of the DOM element.

```
export default class App extends Component {
  render() {
    return (
      <Authenticator hideDefault={true}>
        <MyForm />
      </Authenticator>
    );
  }
}

class MyForm extends Component {
  render() {
    return (
      <Grid>
      {/* more layout goes here */}
      </Grid>
    );
  }
}
```

Hope this helps :)

**Comment by richardzcode** [comment]
Thanks @yuyokk very nice explanation!

**Comment by elorzafe** [comment]
We are going to update the docs for this issue. Please feel free to reopen this issue if the docs are not clear enough.

Thanks!

**Comment by aej11a** [comment]
Workaround in case anyone needs it in the future: wrapping the component giving the error in a React fragment will remove the errors.

ex: 

```
<Authenticator>
    <>
        <div>
             .....
        </div>
    </>
</Authenticator>
```
