### ISSUE TITLE
Missing Document of extra params in Amplify Api

### ISSUE THREAD

**Issue by espelancer** [aws/aws-amplify#344]
Would you mind provide some documentation about what options are available in extra params of Amplify Api?

Based on the Doc of Amazon DynamoDB https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/LegacyConditionalParameters.html
The DynamoDB Api supports KeyConditionExpression and FilterExpression. We can query '>' based on sorted column. Any documentation about how those expressions can be used in Amplify Api?

**Comment by mlabieniec** [comment]
Hi @espelancer currently we don't have built in support for directly querying dynamodb via the client. The recommended approach is to use API module and a lambda proxy for this right now so that you get the benefits of edge / cdn and benefit from context within lambda for extra security. That said, you could use Amplify to do this via manual configuration and query via the aws-sdk, see [here](https://aws.github.io/aws-amplify/media/quick_start.html#aws-services), and I would recommend using the [DocumentClient](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB/DocumentClient.html)

```js
Auth.currentCredentials()
  .then(credentials => {

    // setup the document client
    const db = new DynamoDB.DocumentClient({
      apiVersion: '2012-08-10',
      credentials: Auth.essentialCredentials(credentials)
    });
    
    // query parameters for table
    var params = {
          TableName : 'Table',
           Key: {
               HashKey: 'hashkey'
       }
    };

    // make the db query
    db.get(params, function(err, data) {
      if (err) console.log(err);
      else console.log(data);
    });
````

**Comment by powerful23** [comment]
@espelancer we are closing this issue. If you still have any question about it please feel free to reopen it. Thanks!
