### ISSUE TITLE
How do I pass in the theme when I am using withAuthenticator hoc?

### ISSUE THREAD

**Issue by jfo8000** [aws/aws-amplify#351]
I've got a theme which seems to work when I pass in 
 `<Authenticator theme={AmplifyTheme} />
`
But if I want to use the withAuthenticator hoc instead I can't work out how to pass in the theme?

I would rather style what I've got than replace the UI.... 

(Obviously this is using react.js)

**Comment by richardzcode** [comment]
withAuthenticator actually returns Authenticator component when user not signed in. Passing theme would be something like this:

```
import React from 'react';

class App extends React.Component {
...
}

const AppWithAuth = withAuthenticator(App)

export default AppWithAuth;
```

Then in your `index.js`
```
ReactDOM.render(<App theme={AmplifyTheme} />, document.getElementById('root'));
```

**Comment by jack-wells** [comment]
Hello! Can I make a suggestion that there be a way to pass parameters to the withAuthenticator HOC other than through a call to ReactDOM.render()? I'm trying to use withAuthenticator() with Gatsby, and it hides the ReactDOM.render() call. It would be nice to pass the theme as a parameter to withAuthenticator.

**Comment by jfo8000** [comment]
@surmer - I believe you can wrap any component in withAuthenticator() around any component anywhere in the tree...  it does not particularly have to be the one passed into ReactDom.render().   

I think the main reason the example has it around the entire App is the greetings bar is designed to appear at the top of the screen. But after a bit of lion taming I figured out how to turn it off. 

I found the API description a little confusing until I read the source code to work out how simple it was.  

withAuthenticator is basically just a helper class...  have a look at its guts.
https://github.com/aws/aws-amplify/blob/master/packages/aws-amplify-react/src/Auth/index.jsx

Hope this helps in any way...  Agree the withAuthenticator API probably should take a json object that has all the options.  Would make life significantly clearer.

**Comment by surmer** [comment]
@jfo8000 - appreciate the feedback. I guess that would be my big feature suggestion: some way to pass parameters to the withAuthenticator() HOC like the theme. Also would be nice to wrap the entire app with the wA(), and specify which components don't need to be logged in to display, and which do. For example, I'd love to show that a user is logged out or logged in anywhere in the app, but that some routes are private and are only displayed to those logged in. Hard to use the HOC in this way (afaik of course!), since it seems to want to present a login box in the component you wrap.

But noted that you can wrap any component with wA(). Thanks for the tip on the source code too - the documentation is lagging a bit, and it's a little hard to tell how to use it outside the canonical wrap-the-entire-app use case.

**Comment by jfo8000** [comment]
@surmer - absolutely 100% agree.  Singing from the same song sheet. 

Have a look at the 'checkUser' method inside of Greetings.jsx.  You can pretty much call the Auth libraries from anywhere in your react tree to get the current user.  This is how I wound up calling it from my nav bar component to get the current signed in user.

https://github.com/aws/aws-amplify/blob/master/packages/aws-amplify-react/src/Auth/Greetings.jsx

**Comment by efdornbush** [comment]
@jackwellsxyz @jfo8000 for many of the use cases you've mentioned, it seems like you should be using the Authenticator component directly rather than forcing withAuthenticator to work. With that approach you still wrap the App root component and can then pass the authState to all your sub-components. Then you decide whether or not each sub-component displays its content and what to display instead,rather than trying to offload all of that app-specific logic/rendering to withAuthenticator.
