### ISSUE TITLE
invoke method doesn't work because of "navigator is not defined"

### ISSUE THREAD

**Issue by deruta1992** [aws/aws-amplify#362]
I tried to access my API gateway (generated by AWS Mobile Hub automatically) but following command didn't work: awsmobile cloud-api invoke
Error is as following:
`cloud-api invoke error:
ReferenceError: navigator is not defined
    at Object.<anonymous> (/Users/(username)/.nvm/versions/node/v6.11.3/lib/node_modules/awsmobile-cli/node_modules/aws-amplify/lib/Common/Platform/index.js:21:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/(username)/.nvm/versions/node/v6.11.3/lib/node_modules/awsmobile-cli/node_modules/aws-amplify/lib/Common/index.js:31:18)
    at Module._compile (module.js:570:32)`
I uninstalled aws-amplify, npm cache clear, then installed again, but still not work. Is there any solutions?

**Comment by mlabieniec** [comment]
@deruta1992 where are you making this call from? Is this a browser app or something you are doing in node.js / server?

**Comment by yuyokk** [comment]
I think this one was fixed here https://github.com/aws/aws-amplify/pull/237 but `aws-amplify` dependency within [`awsmobile-cli`](https://github.com/aws/awsmobile-cli/blob/master/package.json) is still not updated.

**Comment by mlabieniec** [comment]
@deruta1992 do you have the latest cli? Which version of the cli are you on?

    awsmobile -V

**Comment by UnleashedMind** [comment]
@yuyokk awsmobile-cli updated the aws-amplify dependency already.

**Comment by yuyokk** [comment]
@UnleashedMind I might be missing something but I see that [`awsmobile-cli`](https://github.com/aws/awsmobile-cli/blob/master/package-lock.json#L201-L202) uses `aws-amplify` with version # `0.2.4`  and according to `aws-amplify` release page, the following release includes the fix I was referring to (https://github.com/aws/aws-amplify/pull/237)

![image](https://user-images.githubusercontent.com/1225343/36659028-bf9ee144-1adb-11e8-8723-08b0c475c775.png)

but when I locally do `npm install` on `awsmobile-cli` I see that fix is not present :(

![image](https://user-images.githubusercontent.com/1225343/36659242-73c717b8-1adc-11e8-9c13-1c5cf743af4c.png)

It seems that npm releases differ from those on github release page.

I tried `npm install --save aws-amplify@0.2.6` and see the fix is there.

**Comment by deruta1992** [comment]
I updated awsmobile-cli and all things went well.
Thanks for your support!
