### ISSUE TITLE
s3.get() returns signed url that expires when access token gets expired

### ISSUE THREAD

**Issue by yuyokk** [aws/aws-amplify#380]
_Do you want to request a feature or report a bug?_

Question/Bug

_What is the current behavior?_

`expires` param was added to `s3.get()` [here](https://github.com/aws/aws-amplify/pull/327).
In my app I set it to 2 years but returned URL fails with an error in an hour

```xml
<Error>
  <Code>ExpiredToken</Code>
  <Message>The provided token has expired.</Message>
</Error>
```

_What is the expected behavior?_

URL is valid for the time specified by `expires` param.

_Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?_

aws-amplify v0.2.9

**Comment by manueliglesias** [comment]
Hi @yuyokk 

Pre-signed URL are only valid as long as the credentials used to sign it are.

This means that the maximum expiration you can use is determined by the credential's expiration.

If you are using Cognito and the Auth category from amplify, the credentials used are temporary (short lived) credentials generated by [AWS STS](https://docs.aws.amazon.com/STS/latest/APIReference/Welcome.html).

This is by design. While I don't know your use case, it might make more sense to generate the pre-signed url only when you want to actually use it (e.g. when a user clicks a "Download" button).

If you want to learn more:
- https://aws.amazon.com/blogs/compute/secure-api-access-with-amazon-cognito-federated-identities-amazon-cognito-user-pools-and-amazon-api-gateway/
- https://docs.aws.amazon.com/cognito/latest/developerguide/authentication-flow.html
- https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_request.html
