### ISSUE TITLE
Developer Authenticated Identities

### ISSUE THREAD

**Issue by stevepsharpe** [aws/aws-amplify#416]
Do you want to request a feature or report a bug?
**question**

I can see in the documentation how to do use the standard Federated identities, I'm unclear how to use Developer Authenticated Identities. I'm trying to get Strava login to work.

I have a lambda function that checks a passed in code from Strava, does the auth and then uses `getOpenIdTokenForDeveloperIdentity` which returns a token and identity id. How do I then use this with Amplify?

**Comment by nidsharm** [comment]
Hey @stevepsharpe ,

Since you have your Auth module built out and inside a lambda function, you should configure Amplify with your AWS resources. You can use this guide: https://github.com/aws/aws-amplify/blob/master/docs/media/api_guide.md to find out the resources required to use our API module. 

You can make REST requests from your app to your endpoint using Amplify API module. 
Please let us know if you have any other questions on this. 

Thanks,
Nidhi

**Comment by buggy** [comment]
@stevepsharpe `federatedSignIn()` doesn't currently support developer authenticated identities. I've create a PR #425 to add support for them. If it's merged then you'll be able to pass the token from your Lambda into `federatedSignIn()` and everything else should work.

I would like to add that while I was initially using developer authenticated identities I'm currently experimenting with using custom authentication flows and Cognito User Pools instead of developer authenticated flows and Cognito Identity Pools. I'm only in the early stages of testing but it looks promising.

**Comment by powerful23** [comment]
Closing this issue as the pr has been merged.
