### ISSUE TITLE
Is AWS-Amplify mature enough for production?

### ISSUE THREAD

**Issue by Tee88** [aws/aws-amplify#579]
Thank you for making Amplify.
1.Amplify's current version is 0.2.11 , is it safe to use it at this stage in production?
2.How soon is AWS IoT expected to come to PubSub?
Thanks in advance.

**Comment by mlabieniec** [comment]
Hi @Tee88 

1. We do have many customers (in the hundreds right now) running production apps with amplify and amplify react native. We have a build phase and are implementing any refactoring etc. to be backwards compatible. If we do any major updates / breaking changes they will be documented and will be major version updates so as to not be pulled down via your package.json.

2. Currently you can use IoT with PubSub, we are working mainly on documentation since the process of setting it up with Cognito can be complex so we are also working with the IoT team to hopefully make this simpler. For now you can:

On your authenticated IAM role add:
AWSIoTDataAccess

Create a Policy in IoT (IoT console - Secure => Policies), for example:

```js
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "iot:*",
      "Resource": "arn:aws:iot:us-east-1:202696340233:*"
    }
  ]
}
```

Attach IoT policy to cognito identity id via cli with you Cognito identity pool ID:
aws iot attach-principal-policy --policy-name AllTopics --principal "us-east-1:xxxx-xxxx"

We are working on automating this with the awsmobile-cli.

**Comment by naseemrafique** [comment]
How Can I attach multiple principals with iot policy. I have multiple identity pools for each stage (dev, qa and prod).
