### ISSUE TITLE
Support Push Notifications for non-ejected CRNA apps

### ISSUE THREAD

**Issue by ankitkante** [aws/aws-amplify#631]
Do you want to request a feature or report a bug?
Feature

What is the current behavior?
The docs mentioned [here](https://aws.github.io/aws-amplify/media/push_notifications_setup.html) describes in detail, how to setup notifications in a react native app. But, from the looks of it, this will not work for non-ejected CRNA apps

What is the expected behavior?
If no support available, then provide support for enabling notifications in non-ejected CRNA apps.
If support is available, then update the documentation so that it describes the steps to configure push notifications in non-ejected CRNA apps.

**Comment by nidsharm** [comment]
Hi @ankitkante ,

Thank you for trying out Amplify. Push notifications cannot be added to non-ejected CRNA apps. This is because there are some differences in how push notifications are handled in iOS and Android. This causes us to update the platform folders of the app for the feature to work.  
Please feel free to re-open this issue if you have any questions.

**Comment by lepirlouit** [comment]
expo has a solution for this : https://docs.expo.io/versions/v29.0.0/guides/push-notifications
