### ISSUE TITLE
S3Image uses path prop inconsistently

### ISSUE THREAD

**Issue by ceich** [aws/aws-amplify#673]
_Do you want to request a feature or report a bug?_
Bug (or else my confusion ;-)

_What is the current behavior?_
When S3Image is given `picker="true"` and `path` props (and not `imgKey`), `handlePick` treats the `path` prop as a prefix, tacking on the result of `calcKey`, when putting the image. However, the `load` method always uses `path` unmodified to get the image. This makes it impossible to give S3Image a single value for `path` that works for both put and get.

_What is the expected behavior?_
I don't understand the use case for the `path` prop, so I can't say. The docs seem to show an upload-only usage, while I want to use S3Image for a "profile picture" editor (display current, allow update). The current code forces me to use `imgKey` exclusively.

_Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?_
0.3.0

**Comment by richardzcode** [comment]
`imgKey` means one thing, the identifier for the existing image.

When rendering a S3Image, there are two cases: 1) already have an image; 2) do not have an image.

In the second case, there is no `imgKey`. by specifying `path` you indicate where the new image should be put. And then `imgKey` is calculated during put.

So basically if you know exactly the uri of the image (existing image or predefined uri like profile image), use `imgKey`. Otherwise use `path` to indicate where should the new image be.

One example of the second use case is to use `S3Image` for an album as an uploader.

**Comment by YikSanChan** [comment]
> In the second case, there is no `imgKey`. by specifying `path` you indicate where the new image should be put. And then `imgKey` is calculated during put.

However, `S3Image` doesn't return back the calculated `imgKey`(because the only data it exposes is through `onLoad`). Then users have no idea (other than reading through the source code and manually repeat the `path + calcKey(data, fileToKey)` logic to calculate `imgKey`) what the `imgKey` is after users upload an image.
