### ISSUE TITLE
How to add required attributes of AWS User pool to AWS amplify react withAuthenticator HOC 

### ISSUE THREAD

**Issue by athJ** [aws/aws-amplify#769]
I am using the new AWS amplify SDK for react, the default UI gives username , password , email and phone number option but I want to remove the phone number attribute and add a name field because my user pool requires a name and not phone number when a user registers , how can I do that ?

**Comment by jdeanwaite** [comment]
What I ended up doing was writing my own custom authentication screens. It takes more time, but it gives you full control of your authentication process. I modeled it after the screens provided in the library, so that way I did not have to spend much time with the logic.

There is also a great video by Nader Dabit [here](https://www.youtube.com/watch?v=5uPNmq8TUoA) where he walks through building his own sign in and sign up components and then manually authenticating using the Amplify library.

**Comment by athJ** [comment]
@jdeanwaite Thanks for the suggestion and the video. I wanted to take advantage of the automatic routing provided in the HOC but its just a wrapper around the Authenticator component so making own components sounds like a good idea.I'll try making my own components and it is a smart idea to adapt the existing logic from the library.

**Comment by emzxcv** [comment]
I'm having the same problem @athJ  have you solved it?

**Comment by athJ** [comment]
@emzxcv I solved it by building my own components in React, the Auth class in this sdk offers some methods that will help you build it .Building it from scratch is the only way if you want to use custom attributes . https://aws-amplify.github.io/amplify-js/api/classes/authclass.html
