### ISSUE TITLE
Converting from amazon-cognito-identity-js

### ISSUE THREAD

**Issue by genestd** [aws/aws-amplify#839]
This seems like a really basic question: I have a project where I have rolled my own auth using the old amazon-cognito-identity-js package.  I am also using Amplify to connect to Pinpoint for analytics.

Right now I have installed both aws-amplify 0.4.0 and amazon-cognito-identity-js 1.31.0 my project. 

I see there is a 2.0.5 version of amazon-cognito-identity-js in the packages directory of this project, but I don't see it in node_modules of my project under aws-amplify. 

`yarn upgrade amazon-cognito-identity-js` doesn't update to version 2.0.5.  How do I install amazon-cognito-identity-js from aws-amplify using yarn?

**Comment by mlabieniec** [comment]
Hi @genestd you should be able to run:

    yarn add amazon-cognito-identity-js@2.0.5

To install as a dependency directly into your project.

**Comment by mlabieniec** [comment]
@genestd no problem!

**Comment by paolavness** [comment]
Hi there, I'm placing this here rather than starting a new thread as its related.

I'd like to upgrade/update our underlying packages to work entirely off Amplify. Right now, we're using the amazon-cognito-identity-js stand alone library - legacy from before Amply Auth existed - and want to integrate new Amplify goodies. Rather than running the scenario of maintaining two packages, I like to create a seemless experience running off the one.

We use have a webapp using Federated Identities, cognito userpools - ie, we're not using the Mobile Hubb.

Is there an 'upgrade' type guide or howto for converting from amazon-cognito-identity-js to Amplify Auth? 

Thank you.
Paola
