### ISSUE TITLE
What is the best way to manage release lifecycle in Amplify?

### ISSUE THREAD

**Issue by BrianSHenderson** [aws/aws-amplify#875]
Is there an efficient way to publish to testing/staging/production using Amplify?

**Comment by cjsauer** [comment]
>You could just utilize multiple environment configurations
Does this mean creating one MobileHub project per environment? If so, are there methods for managing multiple projects using the `awsmobile` CLI tool? 

Also, how does this work on the backend side of things?

**Comment by hrmoller** [comment]
@cjsauer seems as it was added as a feature request on the `awsmobile` repo ~one month ago: https://github.com/aws/awsmobile-cli/issues/114

@mlabieniec `aws-export.js` is added to `.gitignore` when setting up a new project but are there any problems related to having the file added to git (or any other CVS)?

My use case: I want use different backends based on the environment my app is run in. Adding `aws-export.js` to git and replacing the values in that file with environment variables I can load different values into `aws-export.js` through environment variables that are set with different values based on the environment. That solution also makes easy to handle in CI and then again I can avoid using `awsmobile-cli` in CI...?

**Comment by swaminator** [comment]
@hrmoller : I'm a PM on the team. Would love to chat with you further about your usecase. We do not recommend adding the aws-export.js to git and instead recommend using environment variables in your build system. I would love to chat with you if you if you have the time.

**Comment by mlabieniec** [comment]
@cjsauer not directly. What you could do is either use something like grunt/gulp or just npm scripts to symlink the .awsmobilejs folder from an environment specific folder you have in your repo. For example, if you setup a project with the awsmobile-cli, you will end up with a .awsmobilejs folder. You could then rename this folder to .awsmobilejs-dev, and create a symlink .awsmobilejs -> .awsmobilejs-dev. Then within your npm/grunt/gulp script have a command like `npm deploy:dev` and that script would do something like `ln -s .awsmobilejs-dev .awsmobilejs && awsmobile publish`.

Yes you would need to maintain multiple Mobile Hub projects i.e. myproject-dev|staging|prod

@hrmoller we don't recommend committing that file since it contains endpoints for your environment and can expose your aws environments endpoints and arns/IDs etc.

**Comment by jordanranz** [comment]
Closing this issue. Please reopen if @mlabieniec's answer does not suffice or you have more related questions.

**Comment by hrmoller** [comment]
@swaminator I just emailed you😊

**Comment by jadbox** [comment]
@swaminator hey folks, I'm wondering if anything has changed related to managing lifecycles, particularly coming out of the conversations had. My main use-case currently is switching Cognito client_ids depending on the url being using, so I'm considering just overriding `aws_user_pools_web_client_id` based on my project's `.env/.staging` files that are committed in the repo. I'm not wild about committing those client_ids into the repo, but I don't see a clean way of going about this.

**Comment by swaminator** [comment]
@jadbox: I'd be happy to chat with you. Just share your email address here and I'll set something up.

**Comment by swaminator** [comment]
@hrmoller: I don't think we were able to connect either. Can you share your email address?

**Comment by gcid12** [comment]
@swaminator , it would be great if you can keep the conversation going in this ticket. There's a lot of us that have the same question about managing different environments.  Thanks!

**Comment by davidfarinha** [comment]
I also require a multi-environment setup with my Amplify project- where it should be hosted in us-west-2 for dev and eu-west-1 for production. Any advice on this would be much appreciated!

**Comment by jarodsmk** [comment]
If anyone comes across this, I believe this is the solution going forward:

https://github.com/aws-amplify/amplify-cli/issues/508
