### ISSUE TITLE
Not show login first but only before performing some action

### ISSUE THREAD

**Issue by simon998yang** [aws/aws-amplify#924]
Hi , 

I'm using Authenticator from aws-amplify-react , however I don't want to force user to login first, some content should be available to user without login. So I only want to show the login screen once user click some action/link . 

Can you shed some light please?

**Comment by mlabieniec** [comment]
@simon998yang you can use the Authenticator directly, so that you can place it where-ever you like in your app, then manage/check the state yourself:
https://aws.github.io/aws-amplify/media/authentication_guide#using-authenticator-component

You can also use the stateChange event directly on the component params.

**Comment by jordanranz** [comment]
Closing this issue. Please reopen if you have further related questions or comments.
